FROM alpine:3.4

ARG BUILD_CORES

ARG PHP_VER=5.4.45
ARG LIBICONV_VERSION=1.15

LABEL description="PHP image based on Alpine" \
      maintainer="Sandeepone <sandeepone@gmail.com>" \
      php_version="PHP v$PHP_VER built from source" \
      repository.hub="gleez/php" \
      repository.url="https://github.com/gleez/docker-images"

ARG PHP_MIRROR=https://secure.php.net

ARG PHP_CONF=" \
    --with-config-file-path=/usr/local/etc/php \
    --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
    --with-pic \
    --with-pcre-regex=/usr \
    --disable-short-tags \
    --without-readline \
    --enable-bcmath=shared \
    --enable-fpm \
    --enable-ftp \
    --disable-cgi \
    --enable-mysqlnd \
    --enable-mbstring \
    --with-curl \
    --with-curlwrappers \
    --with-libedit \
    --with-openssl \
    --with-iconv=/usr/local \
    --with-gd \
    --with-jpeg-dir \
    --with-png-dir \
    --with-xpm-dir=no \
    --with-freetype-dir \
    --enable-gd-native-ttf \
    --disable-gd-jis-conv \
    --enable-libxml \
    --enable-shmop \
    --with-imap \
    --with-imap-ssl \
    --enable-calendar \
    --enable-bcmath \
    --with-gmp \
    --enable-exif \
    --with-mcrypt \
    --with-mhash \
    --with-zlib \
    --with-bz2 \
    --with-iconv \
    --enable-intl \
    --with-gettext \
    --with-pspell \
    --enable-sockets \
    --with-mysql=mysqlnd \
    --with-mysqli=mysqlnd \
    --with-pdo-mysql=mysqlnd \
    --enable-soap \
    --with-xmlrpc \
    --with-xsl \
    --enable-pcntl \
    --enable-sysvsem \
    --enable-sysvshm \
    --enable-sysvmsg \
    --with-zlib"

ARG PHP_EXT_LIST=" \
    wddx"

ARG CUSTOM_BUILD_PKGS=" \
    freetype-dev \
    gmp-dev \
    libmcrypt-dev \
    icu-dev \
    libpng-dev \
    libwebp-dev \
    gd-dev \
    libjpeg-turbo-dev \
    libxpm-dev \
    libedit-dev \
    libxml2-dev \
    openssl-dev \
    libbz2 \
    sqlite-dev \
    gettext-dev \
    libxslt-dev \
    tzdata \
    geoip-dev \
    imagemagick-dev \
    libmemcached-dev \
    aspell-dev \
    enchant-dev \
    cyrus-sasl-dev \
    imap-dev"

ARG CUSTOM_PKGS=" \
    freetype \
    gmp \
    libmcrypt \
    bzip2-dev \
    icu \
    gettext \
    libxslt \
    geoip \
    imagemagick \
    libmemcached-libs \
    aspell-libs \
    aspell-en \
    enchant \
    libsasl \
    c-client"

COPY rootfs /

# Apply stack smash protection to functions using local buffers and alloca()
# Make PHP's main executable position-independent (improves ASLR security mechanism, and has no performance impact on x86_64)
# Enable optimization (-O2)
# Enable linker optimization (this sorts the hash buckets to improve cache locality, and is non-default)
# Adds GNU HASH segments to generated executables (this is used if present, and is much faster than sysv hash; in this configuration, sysv hash is also generated)
# https://github.com/docker-library/php/issues/272
ENV PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2"
ENV PHP_CPPFLAGS="$PHP_CFLAGS"
ENV PHP_LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie"


RUN NB_CORES=${BUILD_CORES-$(getconf _NPROCESSORS_CONF)} \

### Packages installation
  && BUILD_DEPS=" \
    linux-headers \
    libtool \
    build-base \
    pcre-dev \
    zlib-dev \
    wget \
    gnupg \
    autoconf \
    file \
    gcc \
    g++ \
    libc-dev \
    make \
    pkgconf \
    re2c \
    curl-dev \
    dpkg-dev dpkg \
    ${CUSTOM_BUILD_PKGS}" \

  && apk -U add \
    ${BUILD_DEPS} \
    curl \
    ca-certificates \
    openssl \
    libedit \
    libxml2 \
    libwebp \
    gd \
    pcre \
    zlib \
    tar \
    xz \
    ${CUSTOM_PKGS} \

### Source downloading
  && wget ${PHP_MIRROR}/get/php-${PHP_VER}.tar.gz/from/this/mirror -O /tmp/php-${PHP_VER}.tar.gz \
  && wget ${PHP_MIRROR}/get/php-${PHP_VER}.tar.gz.asc/from/this/mirror -O /tmp/php-${PHP_VER}.tar.gz.asc \
  && wget http://ftp.gnu.org/pub/gnu/libiconv/libiconv-${LIBICONV_VERSION}.tar.gz -O /tmp/libiconv-${LIBICONV_VERSION}.tar.gz \
  && mkdir -p /usr/local/etc/php/conf.d \
  && mkdir -p /usr/src \
  && tar xzvf /tmp/php-${PHP_VER}.tar.gz -C /usr/src \
  && tar xzf /tmp/libiconv-${LIBICONV_VERSION}.tar.gz -C /usr/src \

### GNU Libiconv installation
  && cd /usr/src/libiconv-${LIBICONV_VERSION} \
  && ./configure --prefix=/usr/local \
  && make && make install && libtool --finish /usr/local/lib \

### PHP installation
  && sed -e '/set -- --build\s*=.*/ s/^#*/#/' -i /usr/local/bin/docker-php-ext-configure \
  && mv /usr/src/php-${PHP_VER} /usr/src/php \
  && cd /usr/src/php \
  && export CFLAGS="$PHP_CFLAGS" \
   CPPFLAGS="$PHP_CPPFLAGS" \
   LDFLAGS="$PHP_LDFLAGS" \
  && ./configure ${PHP_CONF} \
  && make -j ${NB_CORES} \
  && make install \

### Strip, clean, install modules
  && { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } \
  && make clean \
  && chmod u+x /usr/local/bin/* \
  && docker-php-ext-install ${PHP_EXT_LIST} \
  && cp /usr/src/php/php.ini-production /usr/local/etc/php/php.ini \
  && pecl update-channels \
  && rm -rf /tmp/pear ~/.pearrc \
  && pecl install apc memcached-2.2.0 redis mongodb-1.2.11 imagick geoip \
  && docker-php-ext-enable apc memcached redis mongodb imagick geoip \
  && pecl clear-cache \

### Add nginx user & group (docker run -t -i gleez/nginx:1.12.0 id nginx)
  && addgroup -S nginx \
	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
  && addgroup -g 3000 -S app \
	&& adduser  -u 3000 -D -S -h /var/www -G app app \

  && mkdir /usr/local/etc/php-fpm.d \
  && cp /usr/local/etc/php-fpm.conf.default /usr/local/etc/php-fpm.d/www.conf \
  && { \
      echo '[global]'; \
      echo 'include=/usr/local/etc/php-fpm.d/*.conf'; \
} | tee /usr/local/etc/php-fpm.conf \
  && { \
    echo '[global]'; \
		echo 'error_log = /proc/self/fd/2'; \
		echo; \
		echo '[www]'; \
		echo '; if we send this to /proc/self/fd/1, it never appears'; \
		echo 'access.log = /proc/self/fd/2'; \
		echo; \
		echo 'clear_env = no'; \
		echo; \
		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
		echo 'catch_workers_output = yes'; \
} | tee /usr/local/etc/php-fpm.d/docker.conf \
  && { \
    echo '[global]'; \
    echo 'daemonize = no'; \
    echo; \
    echo '[www]'; \
    echo '; if we send this to /proc/self/fd/1, it never appears'; \
    echo 'listen = 9000'; \
    echo 'user = nginx'; \
    echo 'group = nginx'; \
    echo 'chdir = /var/www'; \
    echo; \
    echo 'pm = dynamic'; \
    echo 'pm.max_children = 9'; \
    echo 'pm.start_servers = 3'; \
    echo 'pm.max_spare_servers = 4'; \
    echo 'pm.min_spare_servers = 2'; \
    echo 'pm.max_requests = 20'; \
    echo; \
    echo 'php_flag[display_errors] = on'; \
    echo 'php_admin_value[expose_php] = Off'; \
    echo 'php_admin_value[memory_limit] = 128M'; \
} | tee /usr/local/etc/php-fpm.d/zz-docker.conf \
  && sed -i  -e "s/user = nobody/user = nginx/g" /usr/local/etc/php-fpm.d/www.conf \
  && sed -i  -e "s/group = nobody/group = nginx/g" /usr/local/etc/php-fpm.d/www.conf \
  && sed -i  -e "s/listen = 127.0.0.1:9000/listen = 9000/g" /usr/local/etc/php-fpm.d/www.conf \
  && sed -i  -e "s/;daemonize\s*=.*/daemonize = no/g" /usr/local/etc/php-fpm.d/www.conf \
  && sed -i \
    -e "s|upload_max_filesize\s*=.*|upload_max_filesize = 99M|" \
    -e "s|max_file_uploads\s*=.*|max_file_uploads = 20|" \
    -e "s|post_max_size\s*=.*|post_max_size = 99M|" \
    -e "s|;cgi.fix_pathinfo\s*=.*|cgi.fix_pathinfo = 1|" \
    -e "s|;date.timezone\s*=.*|date.timezone = UTC|" \
    -e "s|mail.add_x_header\s*=.*|mail.add_x_header = Off|" \
    -e "s|expose_php\s*=.*|expose_php = Off|" \
    /usr/local/etc/php/php.ini \

# Cleanup
  && apk del ${BUILD_DEPS} \
  && rm -rf /tmp/* /var/cache/apk/* /usr/src/* \
     /usr/include/php \
     /usr/lib/php/build \
     /usr/lib/php/modules/*.a \
     /usr/share/man \
     /usr/share/doc \
     /usr/share/info \
     /usr/share/locale

ENTRYPOINT ["docker-php-entrypoint"]

EXPOSE 9000
WORKDIR /var/www

CMD ["php-fpm"]
